[plugin]
repository = "https://github.com/apetih/LogogramHelper.git"
commit = "f439acdb7eb453b3934fc307a0af8f1aa7a64d31"
owners = ["apetih"]
project_path = "LogogramHelper"
changelog = """
- Update for 7.0
"""
